### ISSUE TITLE
Listing on Mailspring Community?

### ISSUE THREAD

**Issue by CodeMouse92** [jpminor/mailspring-isaac-light-theme#5]
Mailspring just launched an official Discourse community which will house the catalog for themes and plugins, among other things. It would be great to have this theme (and your other themes) listed there: https://community.getmailspring.com/c/themes/9

@jpminor if you join, we can also add you to the Theme Designers group.

**Comment by jpminor** [comment]
@CodeMouse92 - Hi - as you can probably tell from the lack of commits I've moved on from Mailspring - development just wasn't active enough for me and I wasn't really able to theme it 100% to what I would have wanted it to be. That said, feel free to list them, fork them, whatever you want to do!
